my_package:
  target: dev
  outputs:
    dev:
      type: postgres
      #for Windows
      #host: host.docker.internal
      #for Mac
      host: docker.for.mac.host.internal
      user: postgres
      password: ***********
      port: 5432
      dbname: dbt-practice
      schema: dbt-practice-data
      threads: 4
